import { createFileRoute, Link } from "@tanstack/react-router";
import { Nav } from "@/components/site/Nav";
import { Footer } from "@/components/site/Footer";
import { SOUL_DISCLAIMER_TEXT } from "@/lib/souls/disclaimer";

const EFFECTIVE = "May 14, 2026";

export const Route = createFileRoute("/legal/disclaimers")({
  head: () => ({
    meta: [
      { title: "Legal & Disclaimers — Super Agent Skill" },
      {
        name: "description",
        content:
          "Fair use, fictional AI personas (souls), use-at-your-own-risk policy, trademarks, and how to report issues.",
      },
      { property: "og:title", content: "Legal & Disclaimers — Super Agent Skill" },
      {
        property: "og:description",
        content:
          "Our position on fair use, fictional AI personas, accuracy, liability, and takedown requests.",
      },
    ],
  }),
  component: DisclaimersPage,
});

function DisclaimersPage() {
  return (
    <div className="min-h-screen bg-background">
      <Nav />
      <article className="mx-auto max-w-3xl px-6 py-12 md:py-16">
        <span className="font-mono text-xs uppercase tracking-[0.2em] text-primary">Legal</span>
        <h1 className="mt-2 text-3xl font-semibold tracking-tight md:text-4xl">
          Legal &amp; Disclaimers
        </h1>
        <p className="mt-2 text-sm text-muted-foreground">Effective {EFFECTIVE}</p>

        <div className="prose prose-sm dark:prose-invert mt-8 max-w-none space-y-8 text-sm leading-relaxed text-foreground/90">
          <section id="souls">
            <h2 className="text-xl font-semibold">Fictional AI personas (“souls”)</h2>
            <p>
              Souls available on Super Agent Skill are <strong>fictional, AI-generated personas</strong>{" "}
              inspired by publicly available writing, talks, interviews, and commentary about real
              individuals. They are <strong>not</strong> the real people, and they are not affiliated
              with, endorsed by, sponsored by, or representative of those individuals, their
              companies, employers, or any related entity.
            </p>
            <p className="mt-3">{SOUL_DISCLAIMER_TEXT}</p>
          </section>

          <section id="fair-use">
            <h2 className="text-xl font-semibold">Fair use, trademarks, and likeness</h2>
            <p>
              References to real individuals, brands, products, and works are made for{" "}
              <strong>educational, commentary, criticism, research, and parody</strong> purposes,
              which we believe constitute fair use under applicable law (including 17 U.S.C. § 107
              in the United States and analogous doctrines elsewhere). All trademarks, service
              marks, trade names, logos, and likenesses remain the property of their respective
              owners. We claim no ownership over them and do not imply any partnership, sponsorship,
              or endorsement.
            </p>
          </section>

          <section id="accuracy">
            <h2 className="text-xl font-semibold">Accuracy and use at your own risk</h2>
            <p>
              Outputs generated by skills, packs, and souls may be inaccurate, incomplete, biased,
              or out of date. They <strong>do not represent the views, opinions, advice, or
              statements</strong> of any real person referenced. You are solely responsible for
              evaluating outputs and for any decisions or actions taken based on them. The platform
              and its operators disclaim, to the maximum extent permitted by law, all warranties and
              all liability arising from your use of generated content.
            </p>
          </section>

          <section id="no-professional-advice">
            <h2 className="text-xl font-semibold">No professional advice</h2>
            <p>
              Nothing produced by the platform constitutes legal, medical, financial, tax,
              psychological, or other professional advice. Always consult a qualified professional
              for advice tailored to your situation.
            </p>
          </section>

          <section id="user-content">
            <h2 className="text-xl font-semibold">User-contributed skills and souls</h2>
            <p>
              Contributors are responsible for ensuring that the content they upload does not
              infringe third-party rights, does not include private or confidential information, and
              complies with our Terms. We may remove or modify content at our discretion.
            </p>
          </section>

          <section id="takedown">
            <h2 className="text-xl font-semibold">Reporting issues / takedown requests</h2>
            <p>
              If you are a rights holder or a referenced individual and you believe a soul or skill
              should be modified or removed, contact us at{" "}
              <a className="underline" href="mailto:contact@zeroagency.ai">
                contact@zeroagency.ai
              </a>{" "}
              with the URL, your relationship to the matter, and a brief description of the issue.
              We review reports promptly and act in good faith.
            </p>
          </section>

          <section>
            <p className="text-xs text-muted-foreground">
              See also our{" "}
              <Link to="/terms" className="underline">
                Terms &amp; Conditions
              </Link>{" "}
              and{" "}
              <Link to="/privacy" className="underline">
                Privacy Policy
              </Link>
              .
            </p>
          </section>
        </div>
      </article>
      <Footer />
    </div>
  );
}
