import type { Artifact, Governance, Kind } from "@/lib/generate/types";
import { GOVERNANCE, KIND_LABELS } from "@/lib/generate/types";
import type { ImplicitGuardrail } from "@/lib/generate/guardrails";

/* ---------- health report download ---------- */

export interface ReportInput {
  prompt: string;
  baseline: { health: number; precision: number; safety: number; latency: number };
  score: { health: number; precision: number; safety: number; latency: number };
  governance: Governance;
  artifacts: Artifact[];
  implicit: ImplicitGuardrail[];
}

export function buildHealthReportMarkdown(r: ReportInput): string {
  const ts = new Date();
  const fmt = (n: number) => n.toFixed(1);
  const dH = r.score.health - r.baseline.health;
  const dP = r.score.precision - r.baseline.precision;
  const dS = r.score.safety + GOVERNANCE[r.governance].safetyBoost - r.baseline.safety;
  const dL = r.score.latency - r.baseline.latency;
  const sign = (n: number) => (n >= 0 ? "+" : "");
  const groups: Kind[] = ["skill", "playbook", "soul", "guardrail"];
  const counts = Object.fromEntries(
    groups.map((k) => [k, r.artifacts.filter((a) => a.kind === k).length]),
  ) as Record<Kind, number>;

  const lines: string[] = [];
  lines.push(`# Super Agent Skill — Trust Score Report`);
  lines.push(``);
  lines.push(`Generated: ${ts.toISOString()}`);
  lines.push(
    `Governance: **${GOVERNANCE[r.governance].label}** — ${GOVERNANCE[r.governance].blurb}`,
  );
  lines.push(``);
  lines.push(`## Brief`);
  lines.push(``);
  lines.push("> " + (r.prompt.trim() || "(no prompt)").replace(/\n/g, "\n> "));
  lines.push(``);
  lines.push(`## Score deltas`);
  lines.push(``);
  lines.push(`| Metric | Baseline | Final | Δ |`);
  lines.push(`|---|---:|---:|---:|`);
  lines.push(
    `| Health | ${fmt(r.baseline.health)} | ${fmt(r.score.health)} | ${sign(dH)}${fmt(dH)} |`,
  );
  lines.push(
    `| Precision | ${fmt(r.baseline.precision)} | ${fmt(r.score.precision)} | ${sign(dP)}${fmt(dP)} |`,
  );
  lines.push(
    `| Safety (with governance) | ${fmt(r.baseline.safety)} | ${fmt(r.score.safety + GOVERNANCE[r.governance].safetyBoost)} | ${sign(dS)}${fmt(dS)} |`,
  );
  lines.push(
    `| Latency (ms) | ${Math.round(r.baseline.latency)} | ${Math.round(r.score.latency)} | ${sign(dL)}${Math.round(dL)} |`,
  );
  lines.push(``);
  lines.push(`## Stack composition`);
  lines.push(``);
  lines.push(
    `Skills ${counts.skill} · Playbooks ${counts.playbook} · Souls ${counts.soul} · Guardrails ${counts.guardrail} (+${r.implicit.length} implicit)`,
  );
  lines.push(``);
  for (const k of groups) {
    const items = r.artifacts.filter((a) => a.kind === k);
    if (items.length === 0) continue;
    lines.push(`### ${KIND_LABELS[k]} (${items.length})`);
    lines.push(``);
    for (const a of items) {
      lines.push(`- **${a.name}@${a.version}** _(${a.source})_ — ${a.summary}`);
      for (const b of a.bullets) lines.push(`  - ${b}`);
    }
    lines.push(``);
  }
  if (r.implicit.length) {
    lines.push(`### Implicit guardrails (from ${GOVERNANCE[r.governance].label})`);
    lines.push(``);
    for (const g of r.implicit) lines.push(`- **${g.name}** — ${g.why}`);
    lines.push(``);
  }
  lines.push(`---`);
  lines.push(`Report generated by Super Agent Skill.`);
  return lines.join("\n");
}

export function downloadHealthReport(r: ReportInput) {
  if (typeof window === "undefined") return;
  const md = buildHealthReportMarkdown(r);
  const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const stamp = new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19);
  const a = document.createElement("a");
  a.href = url;
  a.download = `superagentskill-health-report-${stamp}.md`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

export async function downloadHealthReportPDF(r: ReportInput) {
  if (typeof window === "undefined") return;
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 48;
  const maxW = pageW - margin * 2;
  let y = margin;

  const newPageIfNeeded = (delta: number) => {
    if (y + delta > pageH - margin) {
      doc.addPage();
      y = margin;
    }
  };
  const writeText = (
    text: string,
    opts: { size?: number; bold?: boolean; color?: [number, number, number]; gap?: number } = {},
  ) => {
    const { size = 11, bold = false, color = [30, 30, 30], gap = 4 } = opts;
    doc.setFont("helvetica", bold ? "bold" : "normal");
    doc.setFontSize(size);
    doc.setTextColor(color[0], color[1], color[2]);
    const lines = doc.splitTextToSize(text, maxW) as string[];
    for (const line of lines) {
      newPageIfNeeded(size + gap);
      doc.text(line, margin, y);
      y += size + gap;
    }
  };
  const hr = () => {
    newPageIfNeeded(12);
    doc.setDrawColor(220);
    doc.line(margin, y, pageW - margin, y);
    y += 12;
  };

  const fmt = (n: number) => n.toFixed(1);
  const sign = (n: number) => (n >= 0 ? "+" : "");
  const dH = r.score.health - r.baseline.health;
  const dP = r.score.precision - r.baseline.precision;
  const dS = r.score.safety + GOVERNANCE[r.governance].safetyBoost - r.baseline.safety;
  const dL = r.score.latency - r.baseline.latency;

  // Header
  writeText("Super Agent Skill — Trust Score Report", { size: 20, bold: true, gap: 6 });
  writeText(`Generated: ${new Date().toLocaleString()}`, {
    size: 9,
    color: [120, 120, 120],
    gap: 2,
  });
  writeText(`Governance: ${GOVERNANCE[r.governance].label}`, {
    size: 10,
    color: [80, 80, 80],
    gap: 2,
  });
  writeText(GOVERNANCE[r.governance].blurb, { size: 9, color: [120, 120, 120] });
  hr();

  // Brief / command
  writeText("Command", { size: 13, bold: true, gap: 6 });
  writeText(r.prompt.trim() || "(no prompt)", { size: 11, color: [40, 40, 40] });
  y += 8;

  // Score table
  writeText("Score deltas", { size: 13, bold: true, gap: 6 });
  const rows: [string, string, string, string][] = [
    ["Metric", "Baseline", "Final", "Δ"],
    ["Health", fmt(r.baseline.health), fmt(r.score.health), `${sign(dH)}${fmt(dH)}`],
    ["Precision", fmt(r.baseline.precision), fmt(r.score.precision), `${sign(dP)}${fmt(dP)}`],
    [
      "Safety",
      fmt(r.baseline.safety),
      fmt(r.score.safety + GOVERNANCE[r.governance].safetyBoost),
      `${sign(dS)}${fmt(dS)}`,
    ],
    [
      "Latency (ms)",
      String(Math.round(r.baseline.latency)),
      String(Math.round(r.score.latency)),
      `${sign(dL)}${Math.round(dL)}`,
    ],
  ];
  const colX = [margin, margin + 200, margin + 300, margin + 400];
  rows.forEach((row, idx) => {
    newPageIfNeeded(18);
    doc.setFont("helvetica", idx === 0 ? "bold" : "normal");
    doc.setFontSize(10);
    doc.setTextColor(40, 40, 40);
    row.forEach((cell, i) => doc.text(cell, colX[i], y));
    y += 16;
    if (idx === 0) {
      doc.setDrawColor(230);
      doc.line(margin, y - 12, pageW - margin, y - 12);
    }
  });
  y += 8;
  hr();

  // Stack composition
  const groups: Kind[] = ["skill", "playbook", "soul", "guardrail"];
  const counts = Object.fromEntries(
    groups.map((k) => [k, r.artifacts.filter((a) => a.kind === k).length]),
  ) as Record<Kind, number>;
  writeText("Stack composition", { size: 13, bold: true, gap: 6 });
  writeText(
    `Skills ${counts.skill} · Playbooks ${counts.playbook} · Souls ${counts.soul} · Guardrails ${counts.guardrail} (+${r.implicit.length} implicit)`,
    { size: 10, color: [80, 80, 80] },
  );
  y += 6;

  for (const k of groups) {
    const items = r.artifacts.filter((a) => a.kind === k);
    if (!items.length) continue;
    writeText(`${KIND_LABELS[k]} (${items.length})`, { size: 12, bold: true, gap: 4 });
    for (const a of items) {
      writeText(`• ${a.name}@${a.version}  (${a.source})`, {
        size: 10,
        bold: true,
        color: [40, 40, 40],
      });
      writeText(`   ${a.summary}`, { size: 10, color: [70, 70, 70] });
      for (const b of a.bullets) writeText(`   – ${b}`, { size: 9, color: [110, 110, 110] });
      y += 2;
    }
    y += 4;
  }

  if (r.implicit.length) {
    writeText(`Implicit guardrails (from ${GOVERNANCE[r.governance].label})`, {
      size: 12,
      bold: true,
      gap: 4,
    });
    for (const g of r.implicit) {
      writeText(`• ${g.name}`, { size: 10, bold: true, color: [40, 40, 40] });
      writeText(`   ${g.why}`, { size: 9, color: [110, 110, 110] });
    }
  }

  // Footer on each page
  const total = doc.getNumberOfPages();
  for (let i = 1; i <= total; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(160, 160, 160);
    doc.text(`Super Agent Skill · Trust Score Report · Page ${i} / ${total}`, margin, pageH - 24);
  }

  const stamp = new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19);
  doc.save(`superagentskill-health-report-${stamp}.pdf`);
}
