import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync, existsSync } from "node:fs";

const {
  buildPluginManifest,
  buildMcpConfig,
  buildSkillPluginManifest,
  validatePluginManifest,
  validateMcpConfig,
  normalizePluginName,
  isValidPluginName,
  PLUGIN_SCHEMA_URL,
  MCP_SCHEMA_URL,
} = await import("../src/lib/plugins/agent-plugins.ts");

test("built manifest is conformant", () => {
  const m = buildPluginManifest({
    name: "Super Agent Skill",
    version: "1.2.3",
    description: "Graded skills.",
    homepage: "https://superagentskill.com",
    license: "MIT",
    keywords: ["a", "b"],
    author: { name: "SAK", url: "https://superagentskill.com" },
  });
  assert.equal(m.$schema, PLUGIN_SCHEMA_URL);
  assert.equal(m.name, "super-agent-skill");
  assert.deepEqual(validatePluginManifest(m), []);
});

test("plugin name constraints (§5.5)", () => {
  assert.ok(isValidPluginName("my-plugin"));
  assert.ok(isValidPluginName("acme.tools"));
  assert.ok(!isValidPluginName("My-Plugin"));
  assert.ok(!isValidPluginName("-start"));
  assert.ok(!isValidPluginName("has--double"));
  assert.ok(!isValidPluginName("too.many..dots"));
  assert.ok(!isValidPluginName(""));
  assert.equal(normalizePluginName("Doc Skill — PDF!"), "doc-skill-pdf");
  assert.equal(normalizePluginName("...."), "sak-plugin");
});

test("fatal manifest violations are reported", () => {
  assert.ok(validatePluginManifest({ name: "x" }).some((e) => e.includes("$schema")));
  assert.ok(
    validatePluginManifest({ $schema: PLUGIN_SCHEMA_URL }).some((e) => e.includes("invalid plugin name")),
  );
  assert.ok(
    validatePluginManifest({ $schema: PLUGIN_SCHEMA_URL, name: "x", mcpServers: {} }).some((e) =>
      e.includes("unknown top-level field: mcpServers"),
    ),
  );
  assert.ok(
    validatePluginManifest({
      $schema: PLUGIN_SCHEMA_URL,
      name: "x",
      author: { nickname: "n" },
    }).some((e) => e.includes("author.nickname")),
  );
  assert.ok(
    validatePluginManifest({ $schema: PLUGIN_SCHEMA_URL, name: "x", keywords: "a" }).some((e) =>
      e.includes("keywords"),
    ),
  );
});

test("mcp.json for the hosted server is conformant", () => {
  const cfg = buildMcpConfig();
  assert.equal(cfg.$schema, MCP_SCHEMA_URL);
  assert.equal(cfg.mcpServers.superagentskill.type, "streamable-http");
  assert.deepEqual(validateMcpConfig(cfg), []);
});

test("mcp.json violations", () => {
  const base = { $schema: MCP_SCHEMA_URL };
  assert.ok(
    validateMcpConfig({ ...base, mcpServers: { a: { type: "http", url: "https://x.dev" } } }).some(
      (e) => e.includes("unknown transport"),
    ),
  );
  assert.ok(
    validateMcpConfig({
      ...base,
      mcpServers: { a: { type: "streamable-http", url: "http://example.com/mcp" } },
    }).some((e) => e.includes("must use https")),
  );
  assert.deepEqual(
    validateMcpConfig({
      ...base,
      mcpServers: { a: { type: "streamable-http", url: "http://localhost:8080/mcp" } },
    }),
    [],
  );
  assert.ok(
    validateMcpConfig({
      ...base,
      mcpServers: {
        a: { type: "streamable-http", url: "https://x.dev/mcp", headers: { Authorization: "Bearer t" } },
      },
    }).some((e) => e.includes("credentials")),
  );
  assert.ok(
    validateMcpConfig({
      ...base,
      mcpServers: { a: { type: "stdio", command: "../bin/server" } },
    }).some((e) => e.includes("plugin root")),
  );
  assert.ok(
    validateMcpConfig({
      ...base,
      mcpServers: { a: { type: "stdio", command: "./bin/server", cwd: "data" } },
    }).some((e) => e.includes("cwd")),
  );
  assert.deepEqual(
    validateMcpConfig({
      ...base,
      mcpServers: { a: { type: "stdio", command: "./bin/server", cwd: "${PLUGIN_DATA}/cache" } },
    }),
    [],
  );
  assert.ok(
    validateMcpConfig({ ...base, mcpServers: {}, extra: 1 }).some((e) =>
      e.includes("unknown top-level field"),
    ),
  );
});

test("per-skill manifest keeps SAK data under our extension namespace", () => {
  const m = buildSkillPluginManifest({
    slug: "code-reviewer",
    name: "Code Reviewer",
    description: "Reviews code.",
    version: "0.3.0",
    tags: ["code", "review"],
    trustScore: 0.87,
  });
  assert.deepEqual(validatePluginManifest(m), []);
  assert.equal(m.extensions["com.superagentskill"].trust_score, 0.87);
});

test("repo root manifests exist and are conformant", () => {
  if (!existsSync("plugin.json")) return; // generated by npm run build:agent-plugin
  assert.deepEqual(validatePluginManifest(JSON.parse(readFileSync("plugin.json", "utf8"))), []);
  assert.deepEqual(validateMcpConfig(JSON.parse(readFileSync("mcp.json", "utf8"))), []);
});
