// Shared brand styling for auth emails — matches SuperAgent Skill visual identity.
export const BRAND = {
  name: 'SuperAgent Skill',
  tagline: 'The marketplace for verified AI agent skills',
  url: 'https://superagentskill.com',
  primary: '#DC2626',
  primaryHover: '#B91C1C',
  ink: '#0F0F14',
  muted: '#55575D',
  subtle: '#8B8D93',
  border: '#EAEAEC',
  bg: '#ffffff',
  surface: '#FAFAFA',
}

export const styles = {
  main: {
    backgroundColor: '#ffffff',
    fontFamily:
      'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif',
    margin: 0,
    padding: '32px 0',
  } as const,
  container: {
    maxWidth: '560px',
    margin: '0 auto',
    padding: '0 24px',
  } as const,
  card: {
    backgroundColor: '#ffffff',
    border: `1px solid ${BRAND.border}`,
    borderRadius: '16px',
    padding: '40px 32px',
  } as const,
  brandRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    marginBottom: '28px',
  } as const,
  brandDot: {
    display: 'inline-block',
    width: '10px',
    height: '10px',
    borderRadius: '50%',
    backgroundColor: BRAND.primary,
    marginRight: '10px',
    verticalAlign: 'middle',
  } as const,
  brandName: {
    fontSize: '15px',
    fontWeight: 700 as const,
    color: BRAND.ink,
    letterSpacing: '-0.01em',
    verticalAlign: 'middle',
  } as const,
  h1: {
    fontSize: '24px',
    fontWeight: 700 as const,
    color: BRAND.ink,
    lineHeight: '1.25',
    margin: '0 0 16px',
    letterSpacing: '-0.02em',
  } as const,
  text: {
    fontSize: '15px',
    color: BRAND.muted,
    lineHeight: '1.6',
    margin: '0 0 20px',
  } as const,
  link: {
    color: BRAND.primary,
    textDecoration: 'underline',
    fontWeight: 500 as const,
  } as const,
  button: {
    backgroundColor: BRAND.primary,
    color: '#ffffff',
    fontSize: '15px',
    fontWeight: 600 as const,
    borderRadius: '10px',
    padding: '13px 24px',
    textDecoration: 'none',
    display: 'inline-block',
    marginTop: '4px',
  } as const,
  code: {
    fontFamily: '"JetBrains Mono", Menlo, Consolas, monospace',
    fontSize: '28px',
    fontWeight: 700 as const,
    color: BRAND.ink,
    letterSpacing: '0.24em',
    backgroundColor: BRAND.surface,
    border: `1px solid ${BRAND.border}`,
    borderRadius: '10px',
    padding: '16px 20px',
    textAlign: 'center' as const,
    margin: '8px 0 24px',
  } as const,
  divider: {
    border: 'none',
    borderTop: `1px solid ${BRAND.border}`,
    margin: '28px 0',
  } as const,
  footer: {
    fontSize: '12px',
    color: BRAND.subtle,
    lineHeight: '1.6',
    margin: '24px 0 0',
    textAlign: 'center' as const,
  } as const,
  footerLink: {
    color: BRAND.subtle,
    textDecoration: 'underline',
  } as const,
}
