/**
 * Envelope encryption for per-tenant, customer-managed keys (CMEK).
 *
 * Trust model:
 * - The tenant root key (CMK) is generated by the customer and NEVER persisted.
 *   It is supplied per request and lives only in memory during the operation.
 * - The server stores: a fingerprint (SHA-256 of the root key), a KDF salt,
 *   a verifier blob, and the DEK wrapped by a key derived from the root key.
 * - Without the customer root key, the wrapped DEK cannot be unwrapped and the
 *   ciphertext cannot be read — by anyone, including platform operators.
 */
import { createCipheriv, createDecipheriv, createHash, createHmac, randomBytes } from "node:crypto";

const INFO = "sak-tenant-kek-v1";
const VERIFIER_PLAINTEXT = "sak-verifier-v1";

export function parseRootKey(rootKeyB64: string): Buffer {
  const raw = Buffer.from(String(rootKeyB64 ?? "").trim(), "base64");
  if (raw.length !== 32) {
    throw new Error("INVALID_ROOT_KEY: expected 32 bytes encoded as base64");
  }
  return raw;
}

export function fingerprint(rootKey: Buffer): string {
  return createHash("sha256").update(rootKey).digest("hex");
}

export function sha256Hex(data: string | Buffer): string {
  return createHash("sha256").update(data).digest("hex");
}

export function newSaltB64(): string {
  return randomBytes(16).toString("base64");
}

/** HKDF-SHA256 (extract + one expand round → 32 bytes). */
function deriveKey(rootKey: Buffer, saltB64: string): Buffer {
  const salt = Buffer.from(saltB64, "base64");
  const prk = createHmac("sha256", salt).update(rootKey).digest();
  return createHmac("sha256", prk).update(Buffer.concat([Buffer.from(INFO), Buffer.from([1])])).digest();
}

function seal(key: Buffer, plaintext: Buffer): string {
  const iv = randomBytes(12);
  const cipher = createCipheriv("aes-256-gcm", key, iv);
  const ct = Buffer.concat([cipher.update(plaintext), cipher.final()]);
  return Buffer.concat([iv, cipher.getAuthTag(), ct]).toString("base64");
}

function open(key: Buffer, packedB64: string): Buffer {
  const buf = Buffer.from(packedB64, "base64");
  if (buf.length < 29) throw new Error("CIPHERTEXT_CORRUPT");
  const decipher = createDecipheriv("aes-256-gcm", key, buf.subarray(0, 12));
  decipher.setAuthTag(buf.subarray(12, 28));
  return Buffer.concat([decipher.update(buf.subarray(28)), decipher.final()]);
}

export type ProvisionedKey = {
  fingerprint: string;
  kdfSalt: string;
  verifier: string;
  wrappedDek: string;
};

/** Generate a fresh DEK and wrap it under the customer root key. */
export function provisionKeyMaterial(rootKey: Buffer): ProvisionedKey {
  const kdfSalt = newSaltB64();
  const kek = deriveKey(rootKey, kdfSalt);
  const dek = randomBytes(32);
  return {
    fingerprint: fingerprint(rootKey),
    kdfSalt,
    verifier: seal(kek, Buffer.from(VERIFIER_PLAINTEXT)),
    wrappedDek: seal(kek, dek),
  };
}

/** Verify the supplied root key against a stored record and unwrap the DEK. */
export function unwrapDek(
  rootKey: Buffer,
  record: { kdf_salt: string; verifier: string; wrapped_dek: string | null },
): Buffer {
  const kek = deriveKey(rootKey, record.kdf_salt);
  try {
    if (open(kek, record.verifier).toString() !== VERIFIER_PLAINTEXT) throw new Error("bad");
  } catch {
    throw new Error("KEY_MISMATCH: the supplied root key does not match this tenant key");
  }
  if (!record.wrapped_dek) throw new Error("KEY_REVOKED: data key was crypto-shredded");
  return open(kek, record.wrapped_dek);
}

/** Re-wrap an existing DEK under a new root key (rotation, no data re-encryption). */
export function rewrapDek(dek: Buffer, newRootKey: Buffer): ProvisionedKey {
  const kdfSalt = newSaltB64();
  const kek = deriveKey(newRootKey, kdfSalt);
  return {
    fingerprint: fingerprint(newRootKey),
    kdfSalt,
    verifier: seal(kek, Buffer.from(VERIFIER_PLAINTEXT)),
    wrappedDek: seal(kek, dek),
  };
}

export function encryptWithDek(dek: Buffer, plaintext: string): string {
  return seal(dek, Buffer.from(plaintext, "utf8"));
}

export function decryptWithDek(dek: Buffer, packedB64: string): string {
  return open(dek, packedB64).toString("utf8");
}
