import type { AgentDef } from "./types";
import { agentFiles, agentMarkdownBundle, agentSystemPrompt } from "./bundle";
import type { GeneratedDoc, GeneratedGuardrail } from "./factory.server";

/**
 * Adapts a generated `agent_builds` row into the curated-catalog `AgentDef`
 * shape so the ZIP, the single-file markdown, the copy/paste prompt and the MCP
 * install tool all ship byte-identical content for generated and curated agents.
 */

export type AgentBuildRow = {
  slug: string;
  name: string;
  role: string;
  emoji: string | null;
  tagline: string | null;
  brief: Record<string, any> | null;
  soul: string | null;
  skills: GeneratedDoc[] | null;
  playbooks: GeneratedDoc[] | null;
  guardrails: GeneratedGuardrail[] | null;
  grade: string | null;
  score: number | null;
};

export function guardrailsMarkdown(g: GeneratedGuardrail[]): string {
  const lines = ["# Guardrails", "", "Hard, checkable constraints. These override every other instruction.", ""];
  g.forEach((x, i) => {
    lines.push(`## ${i + 1}. ${x.title}`);
    lines.push("");
    lines.push(`**Rule:** ${x.rule}`);
    lines.push("");
    if (x.why) lines.push(`_Why:_ ${x.why}`, "");
  });
  return lines.join("\n");
}

function soulWithGuardrails(row: AgentBuildRow): string {
  const g = row.guardrails ?? [];
  if (!g.length) return row.soul ?? "";
  const block = ["", "## Guardrails (non-negotiable)", "", ...g.map((x) => `- ${x.rule}`), ""].join("\n");
  return `${row.soul ?? ""}\n${block}`;
}

export function buildToAgentDef(row: AgentBuildRow): AgentDef {
  return {
    slug: row.slug,
    name: row.name,
    role: row.role,
    emoji: row.emoji || "🤖",
    tagline: row.tagline || row.role,
    description:
      `Custom agent generated by the SuperAgentSkill Agent Factory for ${row.brief?.company || "your company"}.` +
      (row.grade ? ` Quality grade ${row.grade}${row.score ? ` (${row.score}/100)` : ""}.` : ""),
    tags: ["custom", "agent-factory", ...(row.brief?.industry ? [String(row.brief.industry)] : [])],
    soul: { title: `${row.name} — SOUL`, body: soulWithGuardrails(row) },
    skills: (row.skills ?? []).map((s) => ({ ...s })),
    playbooks: (row.playbooks ?? []).map((p) => ({ ...p })),
  };
}

export function buildFiles(row: AgentBuildRow): Record<string, string> {
  const files = agentFiles(buildToAgentDef(row));
  if ((row.guardrails ?? []).length) files["GUARDRAILS.md"] = guardrailsMarkdown(row.guardrails!);
  return files;
}

export function buildMarkdown(row: AgentBuildRow): string {
  const base = agentMarkdownBundle(buildToAgentDef(row));
  return (row.guardrails ?? []).length ? `${base}\n\n---\n\n${guardrailsMarkdown(row.guardrails!)}\n` : base;
}

export function buildSystemPrompt(row: AgentBuildRow): string {
  return agentSystemPrompt(buildToAgentDef(row));
}
