/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkillforgeRouteImport } from './routes/skillforge'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as ForgeRouteImport } from './routes/forge'
import { Route as EvolutionRouteImport } from './routes/evolution'
import { Route as EvaluationRouteImport } from './routes/evaluation'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as MarketplacePackageIdRouteImport } from './routes/marketplace.$packageId'
import { Route as LlmsTxtRouteImport } from './routes/llms.txt'
import { Route as DocsMcpRouteImport } from './routes/docs.mcp'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as AgentsMdRouteImport } from './routes/agents.md'
import { Route as AdminRequestsRouteImport } from './routes/admin.requests'
import { Route as AdminPlansRouteImport } from './routes/admin.plans'
import { Route as AdminPackagesRouteImport } from './routes/admin.packages'
import { Route as AdminAccountsRouteImport } from './routes/admin.accounts'
import { Route as AccountUsageRouteImport } from './routes/account.usage'
import { Route as ForgeReportSlugRouteImport } from './routes/forge.report.$slug'
import { Route as AdminPackagesNewRouteImport } from './routes/admin.packages.new'
import { Route as AdminImportMarkdownRouteImport } from './routes/admin.import.markdown'
import { Route as AdminImportGithubRouteImport } from './routes/admin.import.github'

const SkillforgeRoute = SkillforgeRouteImport.update({
  id: '/skillforge',
  path: '/skillforge',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgeRoute = ForgeRouteImport.update({
  id: '/forge',
  path: '/forge',
  getParentRoute: () => rootRouteImport,
} as any)
const EvolutionRoute = EvolutionRouteImport.update({
  id: '/evolution',
  path: '/evolution',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationRoute = EvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/marketplace/',
  path: '/marketplace/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const MarketplacePackageIdRoute = MarketplacePackageIdRouteImport.update({
  id: '/marketplace/$packageId',
  path: '/marketplace/$packageId',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsTxtRoute = LlmsTxtRouteImport.update({
  id: '/llms/txt',
  path: '/llms/txt',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsMcpRoute = DocsMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => DocsRoute,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsMdRoute = AgentsMdRouteImport.update({
  id: '/agents/md',
  path: '/agents/md',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPackagesRoute = AdminPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccountsRoute = AdminAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AdminRoute,
} as any)
const AccountUsageRoute = AccountUsageRouteImport.update({
  id: '/account/usage',
  path: '/account/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgeReportSlugRoute = ForgeReportSlugRouteImport.update({
  id: '/report/$slug',
  path: '/report/$slug',
  getParentRoute: () => ForgeRoute,
} as any)
const AdminPackagesNewRoute = AdminPackagesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminPackagesRoute,
} as any)
const AdminImportMarkdownRoute = AdminImportMarkdownRouteImport.update({
  id: '/import/markdown',
  path: '/import/markdown',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImportGithubRoute = AdminImportGithubRouteImport.update({
  id: '/import/github',
  path: '/import/github',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/docs': typeof DocsRouteWithChildren
  '/evaluation': typeof EvaluationRoute
  '/evolution': typeof EvolutionRoute
  '/forge': typeof ForgeRouteWithChildren
  '/generate': typeof GenerateRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/skillforge': typeof SkillforgeRoute
  '/account/usage': typeof AccountUsageRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/packages': typeof AdminPackagesRouteWithChildren
  '/admin/plans': typeof AdminPlansRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/agents/md': typeof AgentsMdRoute
  '/api/mcp': typeof ApiMcpRoute
  '/docs/mcp': typeof DocsMcpRoute
  '/llms/txt': typeof LlmsTxtRoute
  '/marketplace/$packageId': typeof MarketplacePackageIdRoute
  '/admin/': typeof AdminIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/admin/import/github': typeof AdminImportGithubRoute
  '/admin/import/markdown': typeof AdminImportMarkdownRoute
  '/admin/packages/new': typeof AdminPackagesNewRoute
  '/forge/report/$slug': typeof ForgeReportSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/docs': typeof DocsRouteWithChildren
  '/evaluation': typeof EvaluationRoute
  '/evolution': typeof EvolutionRoute
  '/forge': typeof ForgeRouteWithChildren
  '/generate': typeof GenerateRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/skillforge': typeof SkillforgeRoute
  '/account/usage': typeof AccountUsageRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/packages': typeof AdminPackagesRouteWithChildren
  '/admin/plans': typeof AdminPlansRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/agents/md': typeof AgentsMdRoute
  '/api/mcp': typeof ApiMcpRoute
  '/docs/mcp': typeof DocsMcpRoute
  '/llms/txt': typeof LlmsTxtRoute
  '/marketplace/$packageId': typeof MarketplacePackageIdRoute
  '/admin': typeof AdminIndexRoute
  '/marketplace': typeof MarketplaceIndexRoute
  '/admin/import/github': typeof AdminImportGithubRoute
  '/admin/import/markdown': typeof AdminImportMarkdownRoute
  '/admin/packages/new': typeof AdminPackagesNewRoute
  '/forge/report/$slug': typeof ForgeReportSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/docs': typeof DocsRouteWithChildren
  '/evaluation': typeof EvaluationRoute
  '/evolution': typeof EvolutionRoute
  '/forge': typeof ForgeRouteWithChildren
  '/generate': typeof GenerateRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/skillforge': typeof SkillforgeRoute
  '/account/usage': typeof AccountUsageRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/packages': typeof AdminPackagesRouteWithChildren
  '/admin/plans': typeof AdminPlansRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/agents/md': typeof AgentsMdRoute
  '/api/mcp': typeof ApiMcpRoute
  '/docs/mcp': typeof DocsMcpRoute
  '/llms/txt': typeof LlmsTxtRoute
  '/marketplace/$packageId': typeof MarketplacePackageIdRoute
  '/admin/': typeof AdminIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/admin/import/github': typeof AdminImportGithubRoute
  '/admin/import/markdown': typeof AdminImportMarkdownRoute
  '/admin/packages/new': typeof AdminPackagesNewRoute
  '/forge/report/$slug': typeof ForgeReportSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/discover'
    | '/docs'
    | '/evaluation'
    | '/evolution'
    | '/forge'
    | '/generate'
    | '/onboarding'
    | '/pricing'
    | '/skillforge'
    | '/account/usage'
    | '/admin/accounts'
    | '/admin/packages'
    | '/admin/plans'
    | '/admin/requests'
    | '/agents/md'
    | '/api/mcp'
    | '/docs/mcp'
    | '/llms/txt'
    | '/marketplace/$packageId'
    | '/admin/'
    | '/marketplace/'
    | '/admin/import/github'
    | '/admin/import/markdown'
    | '/admin/packages/new'
    | '/forge/report/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discover'
    | '/docs'
    | '/evaluation'
    | '/evolution'
    | '/forge'
    | '/generate'
    | '/onboarding'
    | '/pricing'
    | '/skillforge'
    | '/account/usage'
    | '/admin/accounts'
    | '/admin/packages'
    | '/admin/plans'
    | '/admin/requests'
    | '/agents/md'
    | '/api/mcp'
    | '/docs/mcp'
    | '/llms/txt'
    | '/marketplace/$packageId'
    | '/admin'
    | '/marketplace'
    | '/admin/import/github'
    | '/admin/import/markdown'
    | '/admin/packages/new'
    | '/forge/report/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/discover'
    | '/docs'
    | '/evaluation'
    | '/evolution'
    | '/forge'
    | '/generate'
    | '/onboarding'
    | '/pricing'
    | '/skillforge'
    | '/account/usage'
    | '/admin/accounts'
    | '/admin/packages'
    | '/admin/plans'
    | '/admin/requests'
    | '/agents/md'
    | '/api/mcp'
    | '/docs/mcp'
    | '/llms/txt'
    | '/marketplace/$packageId'
    | '/admin/'
    | '/marketplace/'
    | '/admin/import/github'
    | '/admin/import/markdown'
    | '/admin/packages/new'
    | '/forge/report/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DiscoverRoute: typeof DiscoverRoute
  DocsRoute: typeof DocsRouteWithChildren
  EvaluationRoute: typeof EvaluationRoute
  EvolutionRoute: typeof EvolutionRoute
  ForgeRoute: typeof ForgeRouteWithChildren
  GenerateRoute: typeof GenerateRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  SkillforgeRoute: typeof SkillforgeRoute
  AccountUsageRoute: typeof AccountUsageRoute
  AgentsMdRoute: typeof AgentsMdRoute
  ApiMcpRoute: typeof ApiMcpRoute
  LlmsTxtRoute: typeof LlmsTxtRoute
  MarketplacePackageIdRoute: typeof MarketplacePackageIdRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skillforge': {
      id: '/skillforge'
      path: '/skillforge'
      fullPath: '/skillforge'
      preLoaderRoute: typeof SkillforgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forge': {
      id: '/forge'
      path: '/forge'
      fullPath: '/forge'
      preLoaderRoute: typeof ForgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evolution': {
      id: '/evolution'
      path: '/evolution'
      fullPath: '/evolution'
      preLoaderRoute: typeof EvolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation': {
      id: '/evaluation'
      path: '/evaluation'
      fullPath: '/evaluation'
      preLoaderRoute: typeof EvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/marketplace/$packageId': {
      id: '/marketplace/$packageId'
      path: '/marketplace/$packageId'
      fullPath: '/marketplace/$packageId'
      preLoaderRoute: typeof MarketplacePackageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms/txt': {
      id: '/llms/txt'
      path: '/llms/txt'
      fullPath: '/llms/txt'
      preLoaderRoute: typeof LlmsTxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/mcp': {
      id: '/docs/mcp'
      path: '/mcp'
      fullPath: '/docs/mcp'
      preLoaderRoute: typeof DocsMcpRouteImport
      parentRoute: typeof DocsRoute
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/md': {
      id: '/agents/md'
      path: '/agents/md'
      fullPath: '/agents/md'
      preLoaderRoute: typeof AgentsMdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/packages': {
      id: '/admin/packages'
      path: '/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AdminPackagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/accounts': {
      id: '/admin/accounts'
      path: '/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AdminAccountsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/usage': {
      id: '/account/usage'
      path: '/account/usage'
      fullPath: '/account/usage'
      preLoaderRoute: typeof AccountUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forge/report/$slug': {
      id: '/forge/report/$slug'
      path: '/report/$slug'
      fullPath: '/forge/report/$slug'
      preLoaderRoute: typeof ForgeReportSlugRouteImport
      parentRoute: typeof ForgeRoute
    }
    '/admin/packages/new': {
      id: '/admin/packages/new'
      path: '/new'
      fullPath: '/admin/packages/new'
      preLoaderRoute: typeof AdminPackagesNewRouteImport
      parentRoute: typeof AdminPackagesRoute
    }
    '/admin/import/markdown': {
      id: '/admin/import/markdown'
      path: '/import/markdown'
      fullPath: '/admin/import/markdown'
      preLoaderRoute: typeof AdminImportMarkdownRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/import/github': {
      id: '/admin/import/github'
      path: '/import/github'
      fullPath: '/admin/import/github'
      preLoaderRoute: typeof AdminImportGithubRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminPackagesRouteChildren {
  AdminPackagesNewRoute: typeof AdminPackagesNewRoute
}

const AdminPackagesRouteChildren: AdminPackagesRouteChildren = {
  AdminPackagesNewRoute: AdminPackagesNewRoute,
}

const AdminPackagesRouteWithChildren = AdminPackagesRoute._addFileChildren(
  AdminPackagesRouteChildren,
)

interface AdminRouteChildren {
  AdminAccountsRoute: typeof AdminAccountsRoute
  AdminPackagesRoute: typeof AdminPackagesRouteWithChildren
  AdminPlansRoute: typeof AdminPlansRoute
  AdminRequestsRoute: typeof AdminRequestsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminImportGithubRoute: typeof AdminImportGithubRoute
  AdminImportMarkdownRoute: typeof AdminImportMarkdownRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccountsRoute: AdminAccountsRoute,
  AdminPackagesRoute: AdminPackagesRouteWithChildren,
  AdminPlansRoute: AdminPlansRoute,
  AdminRequestsRoute: AdminRequestsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminImportGithubRoute: AdminImportGithubRoute,
  AdminImportMarkdownRoute: AdminImportMarkdownRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DocsRouteChildren {
  DocsMcpRoute: typeof DocsMcpRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsMcpRoute: DocsMcpRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface ForgeRouteChildren {
  ForgeReportSlugRoute: typeof ForgeReportSlugRoute
}

const ForgeRouteChildren: ForgeRouteChildren = {
  ForgeReportSlugRoute: ForgeReportSlugRoute,
}

const ForgeRouteWithChildren = ForgeRoute._addFileChildren(ForgeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DiscoverRoute: DiscoverRoute,
  DocsRoute: DocsRouteWithChildren,
  EvaluationRoute: EvaluationRoute,
  EvolutionRoute: EvolutionRoute,
  ForgeRoute: ForgeRouteWithChildren,
  GenerateRoute: GenerateRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  SkillforgeRoute: SkillforgeRoute,
  AccountUsageRoute: AccountUsageRoute,
  AgentsMdRoute: AgentsMdRoute,
  ApiMcpRoute: ApiMcpRoute,
  LlmsTxtRoute: LlmsTxtRoute,
  MarketplacePackageIdRoute: MarketplacePackageIdRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
