/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkillforgeRouteImport } from './routes/skillforge'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as ForgeRouteImport } from './routes/forge'
import { Route as EvolutionRouteImport } from './routes/evolution'
import { Route as EvaluationRouteImport } from './routes/evaluation'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace.index'
import { Route as MarketplacePackageIdRouteImport } from './routes/marketplace.$packageId'

const SkillforgeRoute = SkillforgeRouteImport.update({
  id: '/skillforge',
  path: '/skillforge',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgeRoute = ForgeRouteImport.update({
  id: '/forge',
  path: '/forge',
  getParentRoute: () => rootRouteImport,
} as any)
const EvolutionRoute = EvolutionRouteImport.update({
  id: '/evolution',
  path: '/evolution',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationRoute = EvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/marketplace/',
  path: '/marketplace/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplacePackageIdRoute = MarketplacePackageIdRouteImport.update({
  id: '/marketplace/$packageId',
  path: '/marketplace/$packageId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/discover': typeof DiscoverRoute
  '/docs': typeof DocsRoute
  '/evaluation': typeof EvaluationRoute
  '/evolution': typeof EvolutionRoute
  '/forge': typeof ForgeRoute
  '/generate': typeof GenerateRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/skillforge': typeof SkillforgeRoute
  '/marketplace/$packageId': typeof MarketplacePackageIdRoute
  '/marketplace/': typeof MarketplaceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/discover': typeof DiscoverRoute
  '/docs': typeof DocsRoute
  '/evaluation': typeof EvaluationRoute
  '/evolution': typeof EvolutionRoute
  '/forge': typeof ForgeRoute
  '/generate': typeof GenerateRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/skillforge': typeof SkillforgeRoute
  '/marketplace/$packageId': typeof MarketplacePackageIdRoute
  '/marketplace': typeof MarketplaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/discover': typeof DiscoverRoute
  '/docs': typeof DocsRoute
  '/evaluation': typeof EvaluationRoute
  '/evolution': typeof EvolutionRoute
  '/forge': typeof ForgeRoute
  '/generate': typeof GenerateRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/skillforge': typeof SkillforgeRoute
  '/marketplace/$packageId': typeof MarketplacePackageIdRoute
  '/marketplace/': typeof MarketplaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/discover'
    | '/docs'
    | '/evaluation'
    | '/evolution'
    | '/forge'
    | '/generate'
    | '/onboarding'
    | '/pricing'
    | '/skillforge'
    | '/marketplace/$packageId'
    | '/marketplace/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/discover'
    | '/docs'
    | '/evaluation'
    | '/evolution'
    | '/forge'
    | '/generate'
    | '/onboarding'
    | '/pricing'
    | '/skillforge'
    | '/marketplace/$packageId'
    | '/marketplace'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/discover'
    | '/docs'
    | '/evaluation'
    | '/evolution'
    | '/forge'
    | '/generate'
    | '/onboarding'
    | '/pricing'
    | '/skillforge'
    | '/marketplace/$packageId'
    | '/marketplace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DiscoverRoute: typeof DiscoverRoute
  DocsRoute: typeof DocsRoute
  EvaluationRoute: typeof EvaluationRoute
  EvolutionRoute: typeof EvolutionRoute
  ForgeRoute: typeof ForgeRoute
  GenerateRoute: typeof GenerateRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  SkillforgeRoute: typeof SkillforgeRoute
  MarketplacePackageIdRoute: typeof MarketplacePackageIdRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skillforge': {
      id: '/skillforge'
      path: '/skillforge'
      fullPath: '/skillforge'
      preLoaderRoute: typeof SkillforgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forge': {
      id: '/forge'
      path: '/forge'
      fullPath: '/forge'
      preLoaderRoute: typeof ForgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evolution': {
      id: '/evolution'
      path: '/evolution'
      fullPath: '/evolution'
      preLoaderRoute: typeof EvolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation': {
      id: '/evaluation'
      path: '/evaluation'
      fullPath: '/evaluation'
      preLoaderRoute: typeof EvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/$packageId': {
      id: '/marketplace/$packageId'
      path: '/marketplace/$packageId'
      fullPath: '/marketplace/$packageId'
      preLoaderRoute: typeof MarketplacePackageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DiscoverRoute: DiscoverRoute,
  DocsRoute: DocsRoute,
  EvaluationRoute: EvaluationRoute,
  EvolutionRoute: EvolutionRoute,
  ForgeRoute: ForgeRoute,
  GenerateRoute: GenerateRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  SkillforgeRoute: SkillforgeRoute,
  MarketplacePackageIdRoute: MarketplacePackageIdRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
